### ISSUE TITLE
Generation of final file seems to reuse all known data

### ISSUE THREAD

**Issue by MichaelRoeder** [dice-group/Eaglet#5]
## Problem

I used eaglet for several datasets. However, when I finished a dataset (with a unique name), the tool generates a final file comprising all the documents - even those from datasets that were not part of my current dataset.

**Comment by MichaelRoeder** [comment]
@Kunal-Jha the problem still persists.

It seems to be caused by the way the final file is generated.
1. The controller generates the final result by passing all documents through the pipe again in line 603 (https://github.com/dice-group/Eaglet/blob/master/src/main/java/org/aksw/simba/eaglet/web/EagletController.java#L603). I am not sure why the pipeline is used again but this question is not interesting for this issue :wink: 
2. For that, it loads the documents using [`generateDocumentList`](https://github.com/dice-group/Eaglet/blob/master/src/main/java/org/aksw/simba/eaglet/web/EagletController.java#L520) 
3. This method calls the recursive [`generateList`](https://github.com/dice-group/Eaglet/blob/master/src/main/java/org/aksw/simba/eaglet/web/EagletController.java#L526) method which goes through the __complete__ `"eaglet_data/result_user"` directory.

The last step contains the problem because the method gathers all documents of all users and joins them into a single file. But it should load the original dataset to get the document URIs and get the files for these documents from the current users directory only (not from all users!).

### Workaround

Before starting a new corpus annotation, delete the content of the `"eaglet_data/result_user"` directory.

**Comment by Kunal-Jha** [comment]
On it !!

**Comment by Kunal-Jha** [comment]
Solved on the development branch!!
