### ISSUE TITLE
User result is not stored

### ISSUE THREAD

**Issue by MichaelRoeder** [dice-group/Eaglet#6]
## Problem

Given a dataset comprising a single document (like [`Employer1.ttl`](https://github.com/dice-group/Eaglet/files/1631795/Employer1.txt)), EAGLET is generating the pipe result file. The user can check the file and add new entities. However, for some reason the user result file is not generated and therefore the final result file contains no documents at all.

I will try to reproduce the problem, locally.

**Comment by MichaelRoeder** [comment]
It is working on my machine (Ubuntu OS). The problem might be bound to Windows. The problem reporting developer had Windows and an empty `https` file in the user result folder. In my local folder, I can see a `https:__www.cnbc.com_1-nif.ttl` containing the data for the single example document (which has the URI `https://www.cnbc.com/2017/05/17/best-companies-to-work-for-in-germany.html#char=0,83`). So the problem might be caused by the `:` character in the file name which is not allowed on windows systems.

**Comment by Kunal-Jha** [comment]
Issue resolved and committed to master!!
